{"uuid":"b7a1cc83-72d3-41ed-b733-6bec60c3650f","historyId":"599dcce2998a6b40b1e38e8c6006cb0a","status":"broken","statusDetails":{"message":"The following error originated from your application code, not from Cypress.\n\n  > Script error.\n\nCypress detected that an uncaught error was thrown from a cross origin script.\n\nWe cannot provide you the stack trace, line number, or file where this error occurred.\n\nCheck your Developer Tools Console for the actual error - it should be printed there.\n\nIt's possible to enable debugging these scripts by adding the `crossorigin` attribute and setting a CORS header.\n\nWhen Cypress detects uncaught errors originating from your application it will automatically fail the current test.\n\nThis behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.","trace":"Error: The following error originated from your application code, not from Cypress.\n\n  > Script error.\n\nCypress detected that an uncaught error was thrown from a cross origin script.\n\nWe cannot provide you the stack trace, line number, or file where this error occurred.\n\nCheck your Developer Tools Console for the actual error - it should be printed there.\n\nIt's possible to enable debugging these scripts by adding the `crossorigin` attribute and setting a CORS header.\n\nWhen Cypress detects uncaught errors originating from your application it will automatically fail the current test.\n\nThis behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.\n    at CommandQueue.run (https://10fastfingers.com/__cypress/runner/cypress_runner.js:173192:21)\n    at CommandQueue.run (https://10fastfingers.com/__cypress/runner/cypress_runner.js:159675:15)\n    at $Cy.runQueue (https://10fastfingers.com/__cypress/runner/cypress_runner.js:160598:14)\n    at cy.<computed> [as visit] (https://10fastfingers.com/__cypress/runner/cypress_runner.js:160680:12)\n    at Context.eval (https://10fastfingers.com/__cypress/tests?p=cypress\\e2e\\10fastFingers\\type.cy.ts:100:12)\n    at __stackReplacementMarker (https://10fastfingers.com/__cypress/runner/cypress_runner.js:160107:13)\n    at runnable.fn (https://10fastfingers.com/__cypress/runner/cypress_runner.js:160859:19)\n    at callFn (https://10fastfingers.com/__cypress/runner/cypress_runner.js:114392:21)\n    at ../driver/node_modules/mocha/lib/runnable.js.Runnable.run (https://10fastfingers.com/__cypress/runner/cypress_runner.js:114379:7)\n    at https://10fastfingers.com/__cypress/runner/cypress_runner.js:167847:30\nFrom previous event:\n    at Object.onRunnableRun (https://10fastfingers.com/__cypress/runner/cypress_runner.js:167830:53)\n    at $Cypress.action (https://10fastfingers.com/__cypress/runner/cypress_runner.js:157066:28)\n    at Runnable.run (https://10fastfingers.com/__cypress/runner/cypress_runner.js:165828:13)\n    at next (https://10fastfingers.com/__cypress/runner/cypress_runner.js:114894:10)\n    at https://10fastfingers.com/__cypress/runner/cypress_runner.js:114938:5\n    at timeslice (https://10fastfingers.com/__cypress/runner/cypress_runner.js:108864:27)"},"stage":"finished","steps":[{"status":"failed","statusDetails":{"message":"The following error originated from your application code, not from Cypress.\n\n  > Script error.\n\nCypress detected that an uncaught error was thrown from a cross origin script.\n\nWe cannot provide you the stack trace, line number, or file where this error occurred.\n\nCheck your Developer Tools Console for the actual error - it should be printed there.\n\nIt's possible to enable debugging these scripts by adding the `crossorigin` attribute and setting a CORS header.\n\nWhen Cypress detects uncaught errors originating from your application it will automatically fail the current test.\n\nThis behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.","trace":"Error: The following error originated from your application code, not from Cypress.\n\n  > Script error.\n\nCypress detected that an uncaught error was thrown from a cross origin script.\n\nWe cannot provide you the stack trace, line number, or file where this error occurred.\n\nCheck your Developer Tools Console for the actual error - it should be printed there.\n\nIt's possible to enable debugging these scripts by adding the `crossorigin` attribute and setting a CORS header.\n\nWhen Cypress detects uncaught errors originating from your application it will automatically fail the current test.\n\nThis behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.\n    at CommandQueue.run (https://10fastfingers.com/__cypress/runner/cypress_runner.js:173192:21)\n    at CommandQueue.run (https://10fastfingers.com/__cypress/runner/cypress_runner.js:159675:15)\n    at $Cy.runQueue (https://10fastfingers.com/__cypress/runner/cypress_runner.js:160598:14)\n    at cy.<computed> [as visit] (https://10fastfingers.com/__cypress/runner/cypress_runner.js:160680:12)\n    at Context.eval (https://10fastfingers.com/__cypress/tests?p=cypress\\e2e\\10fastFingers\\type.cy.ts:100:12)\n    at __stackReplacementMarker (https://10fastfingers.com/__cypress/runner/cypress_runner.js:160107:13)\n    at runnable.fn (https://10fastfingers.com/__cypress/runner/cypress_runner.js:160859:19)\n    at callFn (https://10fastfingers.com/__cypress/runner/cypress_runner.js:114392:21)\n    at ../driver/node_modules/mocha/lib/runnable.js.Runnable.run (https://10fastfingers.com/__cypress/runner/cypress_runner.js:114379:7)\n    at https://10fastfingers.com/__cypress/runner/cypress_runner.js:167847:30\nFrom previous event:\n    at Object.onRunnableRun (https://10fastfingers.com/__cypress/runner/cypress_runner.js:167830:53)\n    at $Cypress.action (https://10fastfingers.com/__cypress/runner/cypress_runner.js:157066:28)\n    at Runnable.run (https://10fastfingers.com/__cypress/runner/cypress_runner.js:165828:13)\n    at next (https://10fastfingers.com/__cypress/runner/cypress_runner.js:114894:10)\n    at https://10fastfingers.com/__cypress/runner/cypress_runner.js:114938:5\n    at timeslice (https://10fastfingers.com/__cypress/runner/cypress_runner.js:108864:27)"},"stage":"finished","steps":[{"status":"failed","statusDetails":{},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1695987166034,"name":"visit https://10fastfingers.com/typing-test/english","stop":1695987167564},{"status":"failed","statusDetails":{},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1695987167563,"name":"uncaught exception Error: Script error.\n\nCypress detected that an uncaught error was thrown from a cross origin script.\n\nWe cannot provide you the stack trace, line number, or file where this error occurred.\n\nCheck your Developer Tools Console for the actual error - it should be printed there.\n\nIt's possible to enable debugging these scripts by adding the `crossorigin` attribute and setting a CORS header.","stop":1695987167564}],"attachments":[],"parameters":[],"start":1695987164593,"name":"\"before each\" hook","stop":1695987167564}],"attachments":[],"parameters":[],"labels":[{"name":"package","value":"cypress\\e2e\\10fastFingers\\type.cy.ts"},{"name":"suite","value":""}],"links":[],"start":1695987164590,"name":"type","fullName":"type","stop":1695987167564}